### ISSUE TITLE
Allow change headers and timeout

### ISSUE THREAD

**Issue by PetrSnobelt** [suyu34/gulp-upload#2]
Will be great if there is options for timeout and headers 
https://github.com/suyu34/gulp-upload/pull/3

**Comment by joooye34** [comment]
Yeah, It has been fixed.

**Comment by HarelM** [comment]
Assuming I'm reading the code right the property `headers` should be used for the options?
Can this be added to the documentation (readme.md)?
Seems like the relevant pull request has it...?
